import NextAuthProvider from "@/providers/NextAuthProvider";
import ReactQueryProviders from "@/providers/ReactQueryProvider";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ModalsProvider } from "@mantine/modals";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Asset Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <ReactQueryProviders>
          <NextAuthProvider>
            <MantineProvider defaultColorScheme="dark">
              <ModalsProvider>{children}</ModalsProvider>
            </MantineProvider>
          </NextAuthProvider>
        </ReactQueryProviders>
        <ToastContainer />
      </body>
    </html>
  );
}
