name: Build & Deploy

on: 
  push:
    branches: ["main"]
    
  workflow_dispatch:

jobs:
  build_and_deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate .env file
        run: echo '${{ secrets.ENV }}' >> .env
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: '.env,src,.next,public/,pm2.deploy.config.js,package*.json'
          target: ${{ secrets.APP_FOLDER }}
      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ${{ secrets.APP_FOLDER }}
            npm install
            pm2 start pm2.deploy.config.js
